---
- hosts: practica
  remote_user: root
  tasks:
  - name: instalar mariadb
    action: shell apt-get -y install mariadb-server mariadb-client
  - name: instalar apache
    action: shell apt-get -y install apache2
  - name: instalar php y librerias
    action: shell apt-get -y install php7.0 libapache2-mod-php7.0
  - name: instalar librería php
    action: shell apt-get -y install php-apcu
  - name: instalar librería php
    action: apt pkg={{ item }} state=installed 
    with_items:
      - php7.0-mysql
      - php7.0-curl
      - php7.0-gd
      - php7.0-intl
      - php-pear
      - php-imagick
      - php7.0-imap
      - php7.0-mcrypt
      - php-memcache
      - php7.0-pspell
      - php7.0-recode
      - php7.0-sqlite3
      - php7.0-tidy
      - php7.0-xmlrpc
      - php7.0-xsl
      - php7.0-mbstring
      - php-gettext
  - name: reiniciar apache
    action: shell service apache2 restart
  - name: cambiar permisos de la carpeta www
    action: shell chown -R alex:root /var/www
  - name: instalar phpmyadmin
    action: shell apt-get -y install phpmyadmin
  - name: crear enlace simbolico de phpmyadmin
    action: shell ln -s /usr/share/phpmyadmin /var/www/html

